### ISSUE TITLE
RocksDB: Attempted to read or write protected memory.

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore#268]
Got this during shutdown while debugging, happened one random time:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at RocksDbSharp.Native.rocksdb_get(IntPtr, IntPtr, Byte[], Int64, IntPtr ByRef, RocksDbSharp.ColumnFamilyHandle)
   at RocksDbSharp.Native.rocksdb_get(IntPtr, IntPtr, Byte[], Int64, RocksDbSharp.ColumnFamilyHandle)
   at RocksDbSharp.RocksDb.Get(Byte[], RocksDbSharp.ColumnFamilyHandle, RocksDbSharp.ReadOptions)
   at Blockcore.Features.Base.Persistence.RocksDb.RocksDbChainStore.GetHeader(Blockcore.Consensus.Chain.ChainedHeader, NBitcoin.uint256)
   at Blockcore.Consensus.Chain.ChainedHeader.get_Header()
   at Blockcore.Features.Wallet.WalletManager.ProcessBlock(Blockcore.Consensus.BlockInfo.Block, Blockcore.Consensus.Chain.ChainedHeader)
   at Blockcore.Features.Wallet.WalletSyncManager.OnProcessBlockAsync(Blockcore.Consensus.BlockInfo.Block, System.Threading.CancellationToken)
   at Blockcore.AsyncWork.AsyncQueue`1+<ConsumerAsync>d__19[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.TaskAwaiter+<>c.<OutputWaitEtwEvents>b__12_0(System.Action, System.Threading.Tasks.Task)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at Blockcore.Utilities.AsyncManualResetEvent+<WaitAsync>d__7.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.TaskAwaiter+<>c.<OutputWaitEtwEvents>b__12_0(System.Action, System.Threading.Tasks.Task)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.__Canon)
   at System.Threading.Tasks.TaskFactory+CompleteOnInvokePromise.Invoke(System.Threading.Tasks.Task)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by sondreb** [comment]
This might have happened here:

```
            lock (this.locker)
            {
                bytes = this.rocksdb.Get(DBH.Key(HeaderTableName, bytes));
            }
```

Withint this method: public BlockHeader GetHeader(ChainedHeader chainedHeader, uint256 hash)

So this might actually be caused simply by a thread performing a read while shutting down?

**Comment by soma42** [comment]
A good candidate for the cause is that when shutting down, RocksDbChainStore is already disposed, which also disposes the rocksdb instance. Since Dispose is not participating in the lock, this can happen depending on the timing of things.

Side node, to this:
 ```
ReadOnlySpan<byte> bytes = hash.ToReadOnlySpan();

            lock (this.locker)
            {
                bytes = this.rocksdb.Get(DBH.Key(HeaderTableName, bytes));
            }
```
Why are the reads and writes locked? On the native db level, you can assume the reads and writes are atomic. The lock looks unnecessary. However, if the lock is indeed needed, the byte/string concatenation can be made more efficient by reusing a single memory location for they key.

**Comment by dangershony** [comment]
Yes I think I confirmed it was a shutdown problem, and it was coming from the WalletSyncManager.
The fix is to monitor the node lifetime in the WalletSyncManager.
