### ISSUE TITLE
Error adding a new account

### ISSUE THREAD

**Issue by Igor-san** [block-core/blockcore#343]
When adding a new account (account 1), the http://localhost:port/Wallets page does not open. Error:

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM8U1G4C1B89", Request id "0HM8U1G4C1B89:00000003": An unhandled exception was thrown by the application.
System.ArgumentException: An item with the same key has already been added. Key: homeNew
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Blockcore.Features.Wallet.UI.Pages.Wallets.ReadWallets() in ...\src\Features\Blockcore.Features.Wallet\UI\Pages\Wallets.razor:line 253
```
   https://github.com/block-core/blockcore/blob/ee7a4ff9da5917f8e6207d4688d82950392837d0/src/Features/Blockcore.Features.Wallet/UI/Pages/Wallets.razor#L253

**Comment by miladsoft** [comment]
I **checked** this case and found no **problem**.
