### ISSUE TITLE
RocksDB crash on shutdown

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore#350]
Another incident of shutdown crash with RocksDB:

```
info: Blockcore.Base.BaseFeature[0]
      Saving chain repository.
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at RocksDbSharp.Native.rocksdb_get(IntPtr, IntPtr, Byte[], Int64, IntPtr ByRef, RocksDbSharp.ColumnFamilyHandle)
   at RocksDbSharp.Native.rocksdb_get(IntPtr, IntPtr, Byte[], Int64, RocksDbSharp.ColumnFamilyHandle)
   at RocksDbSharp.RocksDb.Get(Byte[], RocksDbSharp.ColumnFamilyHandle, RocksDbSharp.ReadOptions)
info   at Blockcore.Features.Base.Persistence.RocksDb.RocksDbChainStore.GetHeader(Blockcore.Consensus.Chain.ChainedHeader, NBitcoin.uint256)
: Blockcore.Base.BaseFeature[0]
      Saving proven header store.
   at Blockcore.Consensus.Chain.ChainedHeader.get_Header()
   at Blockcore.Features.Wallet.WalletManager.ProcessBlock(Blockcore.Consensus.BlockInfo.Block, Blockcore.Consensus.Chain.ChainedHeader)
   at Blockcore.Features.Wallet.WalletSyncManager.OnProcessBlockAsync(Blockcore.Consensus.BlockInfo.Block, System.Threading.CancellationToken)
   at Blockcore.AsyncWork.AsyncQueue`1+<ConsumerAsync>d__19[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.TaskAwaiter+<>c.<OutputWaitEtwEvents>b__12_0(System.Action, System.Threading.Tasks.Task)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at Blockcore.Utilities.AsyncManualResetEvent+<WaitAsync>d__7.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.TaskAwaiter+<>c.<OutputWaitEtwEvents>b__12_0(System.Action, System.Threading.Tasks.Task)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.__Canon)
   at System.Threading.Tasks.TaskFactory+CompleteOnInvokePromise.Invoke(System.Threading.Tasks.Task)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by sondreb** [comment]
The reason why this fails, is that the incoming block processing is attempting to open the RocksDB while the node is already in shutdown mode:

![image](https://user-images.githubusercontent.com/309938/129714430-0e0b34fa-fb86-48b7-9b14-bbc8fc40888c.png)

**Comment by sondreb** [comment]
![image](https://user-images.githubusercontent.com/309938/129714546-ffb020a3-af07-492b-8342-604ac15b3a22.png)

**Comment by sondreb** [comment]
![image](https://user-images.githubusercontent.com/309938/129714628-da72ae27-df26-442b-8e00-1bb5a880c4e9.png)

**Comment by sondreb** [comment]
![image](https://user-images.githubusercontent.com/309938/129714665-3105e376-50c1-4f03-84a2-4b010a59f874.png)

**Comment by sondreb** [comment]
Next launch this issue happened:

![image](https://user-images.githubusercontent.com/309938/129714979-df1f6de2-f682-48df-9c78-40c669a51000.png)
